import express from 'express';
import chatRoutes from "./routes/conversation.route.js";
import messageRoutes from "./routes/message.route.js";
import cors from 'cors';
import cookieParser from 'cookie-parser';
const app = express();
app.use(cors());
app.use(express.json({ limit: '16kb' }));
app.use(express.urlencoded({ extended: true }));
app.use(express.static('public'));
app.use(cookieParser());
app.use("/api/v1/chat/conversations", chatRoutes);
app.use("/api/v1/chat/messages", messageRoutes);
export { app };